#!/usr/bin/env bash
# Wrapper script for clang-format
################################################################################
CMD="clang-format"
args=("$@")
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
hook_dir="$(dirname "$DIR")"
. "$hook_dir/utils"


# Get the file argument if one exists. Assert version as necessary.
function parse_args {
	for arg in "${args[@]}"; do
		if [[ "$arg" == "--version="* ]]; then
			actual="$(clang-format --version | awk '{print $3}')"
			expected="$(echo "$arg" | cut -d '=' -f 2)"
			assert_version "$actual" "$expected"
		elif [ -e "$arg" ]; then
			filename="$arg"
		fi
	done

	if [ -z "$filename" ]; then
		echo "ERR: No file arg found. args =" "${args[@]}"
		exit 1
	fi
}


function clangformat_main {
	check_installed "$CMD"
	parse_args
	diff_formatted "${args[@]}" "$filename"
}

clangformat_main
